
apiVersion: v1
kind: Service
metadata:
  name: road-safety
  labels:
    app: road-safety
spec:
  selector:
    app: road-safety
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
